### ISSUE TITLE
Rou'a - install WSL 2

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#15]
Install WSL 2 e.g. following https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by roaatamimi** [comment]
> Install WSL 2 e.g. following https://docs.microsoft.com/en-us/windows/wsl/install-win10



> Install WSL 2 e.g. following https://docs.microsoft.com/en-us/windows/wsl/install-win10
