### ISSUE TITLE
Mohammad - kubernetes

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#21]
Go through the tutorials in

- https://kubernetes.io/docs/tutorials/hello-minikube/
- https://kubernetes.io/docs/tutorials/kubernetes-basics/

and let me know they are useful, and if they cover the same things.

**Comment by mohshbool** [comment]
I think this is a very useful resource [Kubernetes Tutorial for Beginners by Nana Janashia](https://youtu.be/X48VuDVv0do)
