### ISSUE TITLE
Lina - git

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#25]
Read through what is linked in https://cms-dpoa.github.io/cms-dpoa-getting-started/computing/basic/git.html

As an exercise, make an update to a file in this getting started guide. You can for example correct a typo in the word "instalation" in file `computing/basic/unix-bash.md` which shows in https://cms-dpoa.github.io/cms-dpoa-getting-started/computing/basic/unix-bash.html

You can see the instructions on how to make changes in the files in #6

**Comment by katilp** [comment]
Note that in the instructions in #6, steps 11 and 13 refer to a specific file to be changed. In your case, you would edit the file `computing/basic/git.md` (in step 11), and add and commit that file only (no changes to the table of contents file _toc.yaml) so that the add command in step 13 becomes `git add computing/basic/git.md`

**Comment by katilp** [comment]
After I have merged your commit, you can synchronize your local code area with the updates in the origin, and delete your branch related to that change. You'll do it with

```
git checkout master
git pull
git branch -d your-branch-which-was-merged
```
The first command changes your branch to your current version of master, the second command updates it from the repository of origin (see https://cms-dpoa.github.io/cms-dpoa-getting-started/computing/basic/git-faq.html#updating), and the third deletes the merged branch.

**Comment by linaJazar** [comment]
hello kati .. I'm facing a problem while doing the exercise this command `git clone git@github.com:cms-dpoa/cms-dpoa-getting-started.git` is not working with me .  it gave me this result `The authenticity of host 'github.com (13.234.176.102)' can't be established.`

**Comment by katilp** [comment]
It may be due to the ssh key.  Are you using the WSL2 linux (ubuntu) shell for that command?  Did you set up the ssh authentication? 
The instructions on how to generate the key in Linux are in https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent (under the Linux tab), and how to add it to your github account in https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by linaJazar** [comment]
hello kati .. iI wrote the command you told me about (ls ~/.ssh) and it gave me (id_ed25519  id_ed25519.pub  known_hosts) .. when i copy it and paste it in my github account it tells me that it is invalid .. did i do something wrong?

**Comment by katilp** [comment]
Hi! Do you need further help with this?

**Comment by linaJazar** [comment]
Hello kati .. yes i have a problem
When i was trying to do the practice i noticed that i’m not able to it yet
.. i think that i have to go through the tutorials again .. because it is
harder than i though , and i still didn’t get everything.. like i’m
understanding the theoretical side .. but when it’s came to practice i lost

**Comment by katilp** [comment]
We can have a call today so we can have a look together. Would at 14 CET do for you? Other times are fine as well.

**Comment by linaJazar** [comment]
Yes 15 CET works for me👍🏼 .

**Comment by katilp** [comment]
OK, perfect. See you at 15 then 🙂

**Comment by linaJazar** [comment]
Hello kati can you please send me the link of the meeting

**Comment by katilp** [comment]
I've sent it in an email. See you soon!
