### ISSUE TITLE
Rou'a - git: add WSL2 tips to these pages

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#31]
You can add the very nice tips you provided to these pages. It serves also as an exercise for using git.
I have them here for the record:

> - Make sure the Windows version is up to date.
> - Make sure all drivers are also up to date and installed; By going through
>   1) Settings      
>   2) Update and security     
>   3) View additional Options   
>   4) install and update ALL drivers that are listed.
> - When (if) joining the "Windows Insider Program" I found that it's best to choose the "developer" option (which will be the top/first option) instead of the "recommended" option (which will be the second option on the list).
> - Make sure to enable Virtual Machine Feature from BIOS on start up before entering the " `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart `" command on PowerShell.
> - It's best to install the "ARM64 package" that includes ("wsl_update_arm64" and "wsl_update_x64") after making sure all updates are completed and the PC is rebooted.
> - Make sure to have "Ubuntu 20.04 LTS" and register on it
>   - **Disclaimer**: if you're using Ubuntu for the first time you might think that you're not typing anything while entering your password upon registration; while in fact it's just invisible, after entering password the first time press "Enter" in order to confirm password.
> - Last but not least make sure you're running PowerShell/CMD as an administrator before entering any command.

You can see the instructions on how to make changes in the files in #6

Note that in the instructions in #6, steps 11 and 13 refer to a specific file to be changed. In your case, in step 11, make a new file with these detailed instructions `computing/basic/wsl2-faq.md` and add its name to `_toc.yml` below `unix-bash.md`
```
sections:
      - file: computing/basic/wsl2-faq.md
```
In step 13, add and commit the these two files so that the add command in step 13 becomes `git add computing/basic/wsl2-faq.md _toc.yml`

**Comment by katilp** [comment]
Hi! Do you need further help with this?

**Comment by roaatamimi** [comment]
Hi , yes i need
can we have a brief meeting today ?

**Comment by katilp** [comment]
Sure, at 16 CET?

**Comment by roaatamimi** [comment]
Yes!

**Comment by roaatamimi** [comment]
Its 16:00 CET
Im ready

**Comment by katilp** [comment]
I'm in https://cern.zoom.us/j/68152035898?pwd=S2JvVXBIWUZ5SFN5WnFhR1lwZjZ6dz09
