### ISSUE TITLE
Lina - workflows 

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#35]
The exercise in https://cms-opendata-workshop.github.io/workshop-lesson-docker-preexercises/05-validation/index.html
was a very simple one-step workflow, i.e. a collection of commands.

Have a look at how a similar one-step process is implemented as an automated test in
https://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool/blob/master/.github/workflows/main.yml

This code is an example code for the CMS open data, available also through http://opendata.cern.ch/record/12340

Make a fork of the repository (top right of the github page), and start the test workflow by editing a file and doing a pull request (to your own fork).

In this case, the job does not run on your own computer, but on "runners" that GitHub makes available for testing.

You can monitor the progress of the workflows in the "Actions" tab.

(Note that two workflows start and one of them currently fails).

**Comment by linaJazar** [comment]
hello kati .. can we have meeting tomorrow i have some questions about this issue

**Comment by katilp** [comment]
Sure, would 16:30 CET do?

**Comment by linaJazar** [comment]
Yes it works for me 👍🏼
