### ISSUE TITLE
Lina - click package

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#60]
In the main interface script [interface.py](https://github.com/cernopendata/data-curation/blob/master/cms-YYYY-simulated-datasets/code/interface.py) in the `data-curation/cms-YYYY-simulated-datasets` area, a python package called [click](https://pypi.org/project/click/) is used for the command-line interface.

Install it in on your Linux  with 

`pip3 install -U click`

as instructed in https://pypi.org/project/click/ and run the example python script on your laptop.
See https://click.palletsprojects.com/en/7.x/ for further documentation.

In your local `data-curation` code area (cloned in #53), see what `python3 code/interface.py --help` gives.

**Comment by linaJazar** [comment]
hello kati .. where should i run the example ? on ubuntu ? if on ubontu should i copy it all and pase it one time or i should type lina by line ?
((https://pypi.org/project/click/)) this example

**Comment by katilp** [comment]
Yes, do it on your ubuntu.

Make a new file with the name `hello.py` and copy the contents of the first box after "A Simple Example" in that file and save it.
Then run the command `python hello.py --count=3` on your Ubuntu command line.
You can modify the contents of the file to understand how it works, and then have a look how this is used in the interface.py file.

**Comment by linaJazar** [comment]
hello kati , i need your help can we have a call when you are available ?

**Comment by katilp** [comment]
Sure, we can have a call. Describe here your problem (copy-paste the steps you have taken and the output/error messages) so I can have a look first.

**Comment by linaJazar** [comment]
sorry for the late reply kati .. I didn't notice you have replied .
my problem is with copying the text to the file , I create the file and everything is fine but it doesn't work with me to copy the code to the file

**Comment by katilp** [comment]
For copying the text from the website, you would select the text normally with the mouse, when selected, do Ctrl-c.

For pasting to the `VS Code` editor, where you've opened a new file, do Ctrl-v.
You have VS Code installed, don't you?

For pasting to a command-line editor (such as `vi` or `vim`) you would first enter the edit mode with "i" and the paste with the right-mouse click.

**Comment by linaJazar** [comment]
yea I installed the VS code ..
okay thank you kati i will try to do it if it doesn't work then i will have a call with you
