### ISSUE TITLE
Rou'a - setup minikube

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#63]
Read the  basics of Kubernetes in https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

For local testing, set up a `minikube ` cluster in your local Linux installation, see the links in https://cms-dpoa.github.io/cms-dpoa-getting-started/computing/more/kubernetes.html

**Comment by roaatamimi** [comment]
```
minikube start 
😄  minikube v1.18.1 on Ubuntu 20.04 (amd64)
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh

❌  Exiting due to RSRC_OVER_ALLOC_MEM: Requested memory allocation 16384MB is more than your system limit 3868MB.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=16384mb'
```
minikube start --memory=2200mb
😄  minikube v1.18.1 on Ubuntu 20.04 (amd64)
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.doInfo.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...\``
