### ISSUE TITLE
Lina - get familiar with unix/linux shell

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cms-dpoa-getting-started#8]
Go through https://cms-dpoa.github.io/cms-dpoa-getting-started/computing/basic/unix-bash.html

Think of a possible exercise, write it as a comment to this issue

```
this is code
this is another line of code
```

In the text, ` this is code` and **this bold**

**Comment by linaJazar** [comment]
hello Kati , I'm done with this issue but I don't get how should I write exercises ? do you mean a questions like the ones in the links? or a practice to try what I have learned ?

**Comment by katilp** [comment]
Hello Lina, great to hear! Yes, they can be questions like those in the links. You can just add one or two here below in a new comment. They can be very short and simple. Try them yourself first.

**Comment by linaJazar** [comment]
What would be the output of running the following loop in the data-shell/molecules directory?
`$ for filename in c*
> do
>     os $filename
> done `

a)No files are listed.
b)All files are listed.
c)two files only will be listed
d)Only one file will be listed
e)syntax error

**Comment by linaJazar** [comment]
**what is the right command you will use to find lines that contain the word  " is "  in a file called test.txt ?**
